# Generated by Django 2.1.2 on 2018-10-20 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('mid_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('num_of_votes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'candidate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'election',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('num_members', models.IntegerField()),
            ],
            options={
                'db_table': 'party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('voted', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=30)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.Election')),
                ('first_name', models.OneToOneField(db_column='first_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter_first_name', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.OneToOneField(db_column='last_name', on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter_last_name', to=settings.AUTH_USER_MODEL)),
                ('password', models.OneToOneField(db_column='password', on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter_password', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter_username', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyPolicies',
            fields=[
                ('policies', models.CharField(max_length=100)),
                ('party_name', models.OneToOneField(db_column='party_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user_details.Party')),
            ],
            options={
                'db_table': 'party_policies',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='party',
            name='party_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.Candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.Election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.ForeignKey(blank=True, db_column='party_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.Party'),
        ),
    ]
