# Generated by Django 2.1.2 on 2018-10-20 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20181020_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
