# Generated by Django 2.1.2 on 2018-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_auto_20181021_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.IntegerField(null=True),
        ),
    ]
