# Generated by Django 2.1.2 on 2018-10-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_auto_20181021_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='password',
        ),
    ]
